### ISSUE TITLE
AttributeError: 'module' object has no attribute 'direwolf_agc'

### ISSUE THREAD

**Issue by Reid-n0rc** [tkuester/gr-bruninga#3]
I get the following error when trying to run examples after compiling.

Traceback (most recent call last):
  File "./aprs_uhd.py", line 186, in <module>
    main()
File "./aprs_uhd.py", line 174, in main
    tb = top_block_cls()
  File "./aprs_uhd.py", line 103, in __init__
    self.bruninga_fsk_demod_0 = bruninga.fsk_demod(samp_rate)
  File "/usr/local/lib/python2.7/dist-packages/bruninga/fsk_demod.py", line 83, in __init__
    self.bruninga_direwolf_agc_0_0 = bruninga.direwolf_agc(attack, decay)
AttributeError: 'module' object has no attribute 'direwolf_agc'

**Comment by tkuester** [comment]
Hey, this is a reaaaaaally old project. I removed that block... you might want to check out a few versions back where it's still there. Sadly, not all these work, and I don't have the time to update it right now. Hopefully I can get to this some time soon!

**Comment by antonjan** [comment]
Hi
It seems to work on Gnuradio 3.7 but not on 3.8 same error on 3.8
